# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65780a5aac19b4cdf057a10c17a54760bcb1f10cc483ac48c05147f89a2207bed4bed3d19475f7acbb6ce76572ed89e419e4870b44b42650f93ad7e7add64b10

test:
  secret_key_base: 4972f3fea8fbb92d8f5901dba954a1a62205cb7d9a383ec85d60f7c577c7500d0120f039cf977019bffa4732eed56b5f91520c5ca0a519b4473973e1c7c519bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
